#####################################################################################
# documentation:
# - https://docs.gitea.com/usage/actions/overview
# - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
#####################################################################################

name: Build APK

on:
  push:
    tags:
      - v20**
  workflow_dispatch:  # button shown only when in default branch

# NOT implemented in Gitea!
#permissions:
#  contents: write # allow creating releases

jobs:
  build:
    #if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: docker-node-latest

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "current"
        gradle-home-cache-cleanup: true

    - name: Setup Android SDK
      # https://github.com/android-actions/setup-android
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 12266719

    # https://github.com/r0adkll/sign-android-release/issues/84#issuecomment-1885690080
    - name: "Get & set app and build variables"
      shell: bash
      run: |
        #BUILD_TOOL_VERSION=$(ls /root/.android/sdk/build-tools | tail -n 1)
        #echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
        #echo Last build tool version is: $BUILD_TOOL_VERSION

        OVER=v$(date +%Y.%m.%d)
        [ -z "$OVER" ] && echo "ERROR: empty version detected" && exit 3
        echo "APP_VERSION=${OVER}" >> $GITHUB_ENV
        git_sha_short=$(git rev-parse --short "$GITHUB_SHA")
        echo "git_sha_short=$git_sha_short" >> $GITHUB_ENV
        echo "APP version is: $OVER ($git_sha_short)"

    - name: Build Release APK
      run: |
        mkdir apks
        rm -rf app/build/outputs/apk/
        ./gradlew --no-daemon :app:assembleRelease
        mv -v app/build/outputs/apk/release/*.apk apks/${{vars.APK_NAME_ANTIMALWARE}}.apk

    # https://github.com/marketplace/actions/sign-android-releases-apk
    - name: Sign APK
      id: signAPK
      uses: NoCrypt/sign-android@main
      with:
        releaseDir: apks
        signingKey: ${{ secrets.APK_SIGNING_KEY_64 }}
        keyAlias: ${{ secrets.APK_ALIAS }}
        keyStorePassword: ${{ secrets.APK_KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.APK_KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

    - name: Prep release
      run: |
        cd apks
        sha512sum ${{vars.APK_NAME_ANTIMALWARE}}-signed.apk > ${{vars.APK_NAME_ANTIMALWARE}}-signed.apk.sha512

        REF_NAME=$(echo "${{ github.ref }}" | sed -e 's/refs\/heads\///' -e 's/refs\/tags\/v//' -e 's/release\/v//')
        echo "Cleaned name is ${REF_NAME}"
        echo "branch=${REF_NAME}" >> "$GITHUB_OUTPUT"

        find ${{ github.WORKSPACE }} -name ${{vars.APK_NAME_ANTIMALWARE}}-signed.apk

    - name: Create Release
      uses: "https://code.binbash.rocks:8443/Android/gitea-release@main"
      # https://code.binbash.rocks:8443/Android/gitea-release
      with:
        repo_token: "${{ secrets.LOCAL_TOKEN_REPO_RW }}"
        prerelease: false
        generate_notes: true
        files: |
          ${{ github.WORKSPACE }}/apks/${{vars.APK_NAME_ANTIMALWARE}}-signed.apk
          ${{ github.WORKSPACE }}/apks/${{vars.APK_NAME_ANTIMALWARE}}-signed.apk.sha512


#    - name: Create Release
#      uses: "crowbarmaster/GH-Automatic-Releases@latest"
#      # https://github.com/crowbarmaster/GH-Automatic-Releases
#      with:
#        repo_token: "${{ secrets.LOCAL_TOKEN_REPO_RW }}"
#        #automatic_release_tag: latest
#        prerelease: false
#        generate_notes: true
#        title: "${{ env.APP_VERSION }} (${{ env.git_sha_short }})"
#
#      uses: https://gitea.com/actions/gitea-release-action@v1
#      # https://github.com/akkuman/gitea-release-action
#      with:
#        token: "${{ secrets.LOCAL_TOKEN_REPO_RW }}"
#        tag_name: ${{ env.APP_VERSION }}
#        prerelease: false
#        name: "${{ env.APP_VERSION }} (${{ env.git_sha_short }})"
#        files: |
#          ${{ github.WORKSPACE }}/apks/${{vars.APK_NAME_ANTIMALWARE}}-signed.apk
#          ${{ github.WORKSPACE }}/apks/${{vars.APK_NAME_ANTIMALWARE}}-signed.apk.sha512

