name: Build AXP-Guard

on:
  #push:
  #  branches:
  #    - main
  pull_request:
    types:
      - closed
  workflow_call:      # we want to be triggered from the sync workflow
  workflow_dispatch:  # button shown only when in default branch

jobs:
  build:
    if: github.event.pull_request.merged == true || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle Cache
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true

    - name: Build Release APK
      run: |
        mkdir apks
        rm -rf app/build/outputs/apk/
        ./gradlew --no-daemon --stacktrace :app:assembleRelease
        mv -v app/build/outputs/apk/release/*.apk apks/AXP-Guard.apk

    # https://github.com/r0adkll/sign-android-release/issues/84#issuecomment-1885690080
    - name: "Get & set app and build variables"
      shell: bash
      run: |
        BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
        echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
        echo Last build tool version is: $BUILD_TOOL_VERSION
        # see: https://maven.google.com/web/index.html#com.android.tools.build:aapt2
        #wget -q -O aapt.zip https://dl.google.com/android/maven2/com/android/tools/build/aapt2/8.3.2-10880808/aapt2-8.3.2-10880808-linux.jar
        #unzip aapt.zip aapt2 && chmod +x aapt2
        #OVER=$(./aapt2 dump badging apks/OpenEUICC.apk | grep "VersionName" | sed -e "s/.*versionName='//" -e "s/' .*//")
        OVER=$(date +%Y.%m.%d)
        [ -z "$OVER" ] && echo "ERROR: empty version detected" && exit 3
        echo "APP_VERSION=$OVER" >> $GITHUB_ENV
        git_sha_short=$(git rev-parse --short "$GITHUB_SHA")
        echo "git_sha_short=$git_sha_short" >> $GITHUB_ENV
        echo "APP version is: $OVER ($git_sha_short)"

    # https://github.com/marketplace/actions/sign-android-releases-apk
    - name: Sign APK
      id: signAPK
      uses: NoCrypt/sign-android@main
      with:
        releaseDir: apks
        signingKey: ${{ secrets.APK_SIGNING_KEY_64 }}
        keyAlias: ${{ secrets.APK_ALIAS }}
        keyStorePassword: ${{ secrets.APK_KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.APK_KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

    - name: Hash release APK
      run: |
        cd apks
        sha512sum AXP-Guard-signed.apk > AXP-Guard-signed.apk.sha512
        
    - name: Create Release
      uses: "crowbarmaster/GH-Automatic-Releases@latest"
      # https://github.com/crowbarmaster/GH-Automatic-Releases
      with:
        repo_token: "${{ secrets.AXP_GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.APP_VERSION }}"
        prerelease: false
        title: "${{ env.APP_VERSION }} (${{ env.git_sha_short }})"
        files: |
          ${{ github.WORKSPACE }}/apks/AXP-Guard-signed.apk
          ${{ github.WORKSPACE }}/apks/AXP-Guard-signed.apk.sha512

#    - name: Create Release
#      # https://github.com/softprops/action-gh-release
#      uses: "softprops/action-gh-release@v2"
#      with:
#        token: "${{ secrets.AXP_GITHUB_TOKEN }}"
#        name: "${{ env.OPENEUICC_VERSION }} (${{ env.git_sha_short }})"
#        tag_name: "${{ env.OPENEUICC_VERSION }}"
#        prerelease: false
#        make_latest: true
#        #body: # will be pre-pended to release notes!
#        generate_release_notes: true
#        files: |
#          ${{ github.WORKSPACE }}/apks/OpenEUICC-signed.apk
#          ${{ github.WORKSPACE }}/apks/OpenEUICC-signed.apk.sha256
#          ${{ github.WORKSPACE }}/apks/EasyEUICC-signed.apk
#          ${{ github.WORKSPACE }}/apks/EasyEUICC-signed.apk.sha256
#          ${{ github.WORKSPACE }}/apks/OpenEUICC_hidden-signed.apk
#          ${{ github.WORKSPACE }}/apks/OpenEUICC_hidden-signed.apk.sha256

#    - name: Upload signed APKs (latest)
#      # https://github.com/crowbarmaster/GH-Automatic-Releases
#      uses: "crowbarmaster/GH-Automatic-Releases@latest"
#      with:
#        repo_token: "${{ secrets.AXP_GITHUB_TOKEN }}"
#        automatic_release_tag: "latest"
#        overwrite_tag: true
#        prerelease: false
#        title: "${{ env.OPENEUICC_VERSION }} (${{ env.git_sha_short }})"
#        files: |
#          ${{ github.WORKSPACE }}/apks/OpenEUICC-signed.apk
#          ${{ github.WORKSPACE }}/apks/OpenEUICC-signed.apk.sha256
#          ${{ github.WORKSPACE }}/apks/EasyEUICC-signed.apk
#          ${{ github.WORKSPACE }}/apks/EasyEUICC-signed.apk.sha256
#          ${{ github.WORKSPACE }}/apks/OpenEUICC_hidden-signed.apk
#          ${{ github.WORKSPACE }}/apks/OpenEUICC_hidden-signed.apk.sha256
